### DISCUSSION TITLE
Show your configs!

### DISCUSSION THREAD

**Discussion by jacek-kurlit** [jacek-kurlit/pik#150] [Show and tell]
Since pik allow for UI customization
I invite you to share your configuration and screenshots with community

**Comment by Axlefublr** [comment]
![image](https://github.com/user-attachments/assets/82e0eedf-34cd-489f-8d07-bb41f1338d0b)

very minimal theme that uses the orange colors that I use in a lot of other places

**Reply by Axlefublr** [reply]
```toml
screen_size = 'fullscreen'

[ui]
use_icons = true

[ui.process_table]
border = { type = 'Plain', style = { fg = '#d4be98' } }

[ui.process_table.row]
selected_symbol = ' '
even = { fg = '#d4be98' }
odd = { fg = '#d4be98' }
selected = { bg = '#5f472d', add_modifier = 'BOLD' }

[ui.process_table.cell]
# normal = {}
highlighted = { fg = '#e49641', add_modifier = 'BOLD' }
```
