### ISSUE TITLE
allow to configure the colors of the ui

### ISSUE THREAD

**Issue by Axlefublr** [jacek-kurlit/pik#138]
are there any plans for this? I appreciate that you use custom colors, as that removes the possibility of the user's theme not working correctly, but I would love to customize the colors to my preferences. any plans for that?

**Comment by jacek-kurlit** [comment]
Hi,
Yes I had plan for that but I'm not sure how long it will take to implement this.
Can you share with me your vision of better UI and themes?
Creating aesthetic look is kinda hard for me.

**Comment by Axlefublr** [comment]
all I want personally is to be able to change the follwing colors:
foreground text
foreground text when on an alternate row (optionally)
background color of row
alternate background color of row
border color

**Comment by Axlefublr** [comment]
otherwise imo the default color choices look good! they just happen to not be my theme that I use absolutely everywhere, so being able to have things conform would be nice! :3

**Comment by jacek-kurlit** [comment]
Picking this up

**Comment by net** [comment]
@jacek-kurlit love this tool ❤️

For color customization, it would be ideal if both codes `0`-`255` and hex codes were supported.

Also, would you potentially be open to a PR changing some of the UI characters? I think there's room for some parts to look a bit cleaner :)

**Comment by jacek-kurlit** [comment]
@net Hi
If you have any idea on how to improve UI then go for it

**Comment by jacek-kurlit** [comment]
As for supporting color formats it will be hex and names (like "Yellow", "Blue" etc) as this is supported out of the box by ratatui

**Comment by jacek-kurlit** [comment]
Config added
Refer to https://github.com/jacek-kurlit/pik/blob/main/config.md

Please let me know if something need fix or improvement
Also don't forget to share screenshot after you are done, thx!

**Comment by Axlefublr** [comment]
fyi configuring border type doesn't work; tested on foot and kitty

**Comment by Axlefublr** [comment]
ohhhhhh wait you probably didn't release the new version yet, duh

**Comment by Axlefublr** [comment]
wait no you did 🤔

**Comment by Axlefublr** [comment]
oh I see, cargo doesn't see 0.18, only sees 0.17; guessing I just need to wait

**Comment by jacek-kurlit** [comment]
Sorry pipline failed, try now

**Comment by Axlefublr** [comment]
by god that is the most relatable thing about development haha \
and the classic "ci" commit message

alright so far works!! will share my config and a screenshot when I configure it

**Comment by Axlefublr** [comment]
I would expect the border setting to apply to the box below as well (I ***loathe*** the rounded border)

![Image](https://github.com/user-attachments/assets/efb71030-ca33-49af-83f2-71934601288a)

**Comment by Axlefublr** [comment]
insignificant nitpick, but would be cool to be able to specify modifiers in lowercase, like `bold` rather than `BOLD`

**Comment by Axlefublr** [comment]
and the border type too, being able to just do `plain` rather than `Plain`

**Comment by Axlefublr** [comment]
![Image](https://github.com/user-attachments/assets/eafde482-db00-4d95-ba97-dee9325ffa22)

awesome I love this

```toml
screen_size = 'fullscreen'

[ui]
use_icons = true

[ui.process_table]
border = { type = 'Plain', style = { fg = '#d4be98' } }

[ui.process_table.row]
selected_symbol = ' '
even = { fg = '#d4be98' }
odd = { fg = '#d4be98' }
selected = { bg = '#5f472d', add_modifier = 'BOLD' }

[ui.process_table.cell]
# normal = {}
highlighted = { fg = '#e49641', add_modifier = 'BOLD' }
```
